In [1]:
import pandas as pd
import seaborn as sns 
import pandas as pd
import numpy as np
from random import sample

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

## Bagging

Uma técnica que tem como objetivos aprimorar a acurácia e evitar o overfiting, reduzindo a variância. A partir dela, construimos várias vezes o mesmo modelo base para diferentes conjuntos de dados da mesma base de treinamento, obtendo uma estimativa final através da média dos resultados dos modelos base. O Bagging pode ser aplicado com diferentes algoritmos de machine learning, sendo flexível em sua escolha.

## Passo a Passo e Implementação

### Bootstrap

Temos uma base disponível. Dessa base, realizaremos uma amostragem com reposição (bootstrap) e geraremos novas bases uniformes, aleatórias e com reposição. Sendo a quantidade e tamanho das bases a ser definidas de antemão.

In [2]:
df = sns.load_dataset('penguins')
df.dropna(inplace = True)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
4       3450.0  Female  
5       3650.0    Male

In [3]:
# exclui uma das espécies para facilitar o entendimento
df.drop(df.query('species == "Chinstrap"').index, inplace = True)
df.species.value_counts()

Adelie    146
Gentoo    119
Name: species, dtype: int64

In [4]:
alt = {'Adelie' : 0, 'Gentoo' : 1}
df.species = df.species.map(alt)
df.species.value_counts()

0    146
1    119
Name: species, dtype: int64

In [5]:
def bootstrap(base, amostras):
    subdf_X = []
    subdf_y = []
        
    for i in range(0,int(len(base)/amostras)):
        subbase = base.sample(int(len(base)/amostras))
        X = subbase.drop(['species', 'island', 'sex'], axis = 1)
        y = subbase.species
        subdf_X.append(X)
        subdf_y.append(y)
                
    return subdf_y, subdf_X

In [6]:
subdf_y, subdf_X = bootstrap(df, 35)
subdf_X[1]

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
267            50.5           15.9              225.0       5400.0
77             37.2           19.4              184.0       3900.0
223            50.0           15.2              218.0       5700.0
0              39.1           18.7              181.0       3750.0
255            48.4           16.3              220.0       5400.0
312            45.5           14.5              212.0       4750.0
133            37.5           18.5              199.0       4475.0

### Modelagem

Então escolheremos nosso modelo para classificação ou regressão, como por exemplo árveore de decisão. O modelo escolhido será aplicado para cada nova base gerada no passo anterior

In [7]:
# arvore de decisão

def modelagem(subdf_y, subdf_X):
    arvores = []
    for i in range(0,int(len(subdf_y))):
        clf = tree.DecisionTreeClassifier(random_state = 1234)
        clf = clf.fit(subdf_X[i], subdf_y[i])
        y_pred = clf.predict(subdf_X[i])
        arvores.append(y_pred)
                   
    return arvores

In [8]:
arvores = modelagem(subdf_y, subdf_X)
arvores

[array([0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([1, 0, 1, 0, 1, 1, 0], dtype=int64),
 array([1, 1, 0, 1, 1, 1, 1], dtype=int64),
 array([1, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 1, 0, 0, 1, 1, 0], dtype=int64),
 array([0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 1, 0, 1, 1, 1, 1], dtype=int64)]

### Aggregating

Após ajustarmos os modelos na etapa anterior, combinamos os resultados por sua média (para modelos de regressão) ou por votação (para modelos de classificação).

In [9]:
def agrega(subdf_X, subdf_y, arvores):
    df_pred = pd.DataFrame()

    for i in range(0,int(len(subdf_X))):
        subdf_X[i]['original'] = subdf_y[i]
        subdf_X[i]['predito'] = arvores[i]

        for j in range(0,int(len(subdf_X))):

            df_pred = pd.concat([df_pred,subdf_X[j]])

    return df_pred.groupby(['original', 'predito'])[['original', 'predito']].count()


In [10]:
agrega(subdf_X, subdf_y, arvores)

original  predito
original predito                   
0.0      0.0           104      104
1.0      1.0            92       92